# Generated by Django 5.0.6 on 2024-06-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_character_char_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='char_description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='character',
            name='char_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
